# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\H.Ali\Desktop\Auto mux mkv\UI\maingui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 690)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(650, 690))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        Form.setAcceptDrops(False)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.folder_path_LE = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.folder_path_LE.setFont(font)
        self.folder_path_LE.setAcceptDrops(True)
        self.folder_path_LE.setText("")
        self.folder_path_LE.setDragEnabled(False)
        self.folder_path_LE.setObjectName("folder_path_LE")
        self.horizontalLayout.addWidget(self.folder_path_LE)
        self.search_btn = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.search_btn.setFont(font)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.output_path_LE = QtWidgets.QLineEdit(Form)
        self.output_path_LE.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.output_path_LE.setFont(font)
        self.output_path_LE.setAcceptDrops(True)
        self.output_path_LE.setText("")
        self.output_path_LE.setDragEnabled(False)
        self.output_path_LE.setObjectName("output_path_LE")
        self.horizontalLayout_2.addWidget(self.output_path_LE)
        self.search_output_btn = QtWidgets.QPushButton(Form)
        self.search_output_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.search_output_btn.setFont(font)
        self.search_output_btn.setObjectName("search_output_btn")
        self.horizontalLayout_2.addWidget(self.search_output_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.default_cbox = QtWidgets.QComboBox(Form)
        self.default_cbox.setObjectName("default_cbox")
        self.default_cbox.addItem("")
        self.default_cbox.addItem("")
        self.horizontalLayout_3.addWidget(self.default_cbox)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.forced_cbox = QtWidgets.QComboBox(Form)
        self.forced_cbox.setObjectName("forced_cbox")
        self.forced_cbox.addItem("")
        self.forced_cbox.addItem("")
        self.horizontalLayout_3.addWidget(self.forced_cbox)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.language_cbox = QtWidgets.QComboBox(Form)
        self.language_cbox.setObjectName("language_cbox")
        self.language_cbox.addItem("")
        self.language_cbox.addItem("")
        self.horizontalLayout_3.addWidget(self.language_cbox)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.delay_LE = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.delay_LE.setFont(font)
        self.delay_LE.setAcceptDrops(False)
        self.delay_LE.setInputMethodHints(QtCore.Qt.ImhNone)
        self.delay_LE.setObjectName("delay_LE")
        self.horizontalLayout_3.addWidget(self.delay_LE)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.name_LE = QtWidgets.QLineEdit(Form)
        self.name_LE.setAcceptDrops(False)
        self.name_LE.setObjectName("name_LE")
        self.horizontalLayout_3.addWidget(self.name_LE)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.start_btn = QtWidgets.QPushButton(Form)
        self.start_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout_4.addWidget(self.start_btn)
        self.delete_chbox = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.delete_chbox.setFont(font)
        self.delete_chbox.setObjectName("delete_chbox")
        self.horizontalLayout_4.addWidget(self.delete_chbox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.output_PTE = QtWidgets.QPlainTextEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.output_PTE.setFont(font)
        self.output_PTE.setAcceptDrops(False)
        self.output_PTE.setReadOnly(True)
        self.output_PTE.setObjectName("output_PTE")
        self.gridLayout.addWidget(self.output_PTE, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.search_btn, self.folder_path_LE)
        Form.setTabOrder(self.folder_path_LE, self.search_output_btn)
        Form.setTabOrder(self.search_output_btn, self.output_path_LE)
        Form.setTabOrder(self.output_path_LE, self.default_cbox)
        Form.setTabOrder(self.default_cbox, self.forced_cbox)
        Form.setTabOrder(self.forced_cbox, self.language_cbox)
        Form.setTabOrder(self.language_cbox, self.delay_LE)
        Form.setTabOrder(self.delay_LE, self.name_LE)
        Form.setTabOrder(self.name_LE, self.delete_chbox)
        Form.setTabOrder(self.delete_chbox, self.start_btn)
        Form.setTabOrder(self.start_btn, self.output_PTE)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Auto add sub to video"))
        self.label.setText(_translate("Form", "Video Path Folder :"))
        self.folder_path_LE.setPlaceholderText(_translate("Form", "Type your path or use the Search Button"))
        self.search_btn.setText(_translate("Form", "Search"))
        self.label_7.setText(_translate("Form", "Output Path Folder :"))
        self.output_path_LE.setPlaceholderText(_translate("Form", "Leave it Blank will Create \"Done\" Folder in your path with your mux files"))
        self.search_output_btn.setText(_translate("Form", "Search"))
        self.label_2.setText(_translate("Form", "Default:"))
        self.default_cbox.setItemText(0, _translate("Form", "Yes"))
        self.default_cbox.setItemText(1, _translate("Form", "No"))
        self.label_3.setText(_translate("Form", "Forced:"))
        self.forced_cbox.setItemText(0, _translate("Form", "Yes"))
        self.forced_cbox.setItemText(1, _translate("Form", "No"))
        self.label_4.setText(_translate("Form", "Lang:"))
        self.language_cbox.setItemText(0, _translate("Form", "ara"))
        self.language_cbox.setItemText(1, _translate("Form", "eng"))
        self.label_5.setText(_translate("Form", "Delay(in ms):"))
        self.delay_LE.setText(_translate("Form", "0"))
        self.label_6.setText(_translate("Form", "FanSub Name:"))
        self.name_LE.setText(_translate("Form", "Arabic"))
        self.start_btn.setText(_translate("Form", "Start Mux"))
        self.delete_chbox.setText(_translate("Form", "Delete Original Files After Finish?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
